server:
  port: 8081
spring:
  security:
    saml2:
      relyingparty:
        registration:
          # 依赖方的实体ID，任意的值，你可以选择它来区分不同的注册
          # http://localhost:8081/saml2/authenticate/keycloak
          keycloak:
            entity-id:
            # 签名证书，用于验证SAML响应
            signing.credentials:
              # 私钥文件位置
              - private-key-location: classpath:credentials/rp-private.key
                # 证书文件位置
                certificate-location: classpath:credentials/rp-certificate.crt
            # 断言方元数据访问地址
            assertingparty.metadata-uri: http://localhost:8080/realms/myrealm/protocol/saml/descriptor
            # 登出配置
            # SP元数据：http://localhost:8081/saml2/service-provider-metadata/keycloak
            singlelogout:
              binding: POST
              url: "{baseUrl}/logout/saml2/slo"
