server:
  port: 9091
  servlet:
    context-path: /demo

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # session ????
  session:
    # session ??????, ?????? spring-session ????, ??? none, ?????? session ?? redis ????
    store-type: none
    # session ????
    timeout: PT300s
# ums core
ums:
  # ================ ??????????? ================
  oauth:
    # ?????????????, ??: true
    enabled: true
    # ??????, ?? JDK11, ??: false , ??? WARNING: An illegal reflective access operation has occurred ???, ???????, ????????.
    suppress-reflect-warning: true
    # ??????: providerId, ???? JustAuth ??????????, ??? 32 ????????
    github:
      # ??????? clientId ??????? JustAuth ? AuthXxxRequest
      client-id: 4d4ee00e82f669f2ea8d
      client-secret: 953ddbe871a08d6924053531e89ecc01d87195a8
    # ????
    gitee:
      # ???ID
      client-id: 29f5c36c2f4576478e7acd9de476357cc225e7c7683b86510d29072276efc0e2
      # ?????
      client-secret: 767bf7931269eaa9cca8a3c01fcf23b65c423d1dc99fb6db6d5c61f30a38caa2
    # ????????? url ??, ??? ServletContextPath???? /auth2/authorization.
    auth-login-url-prefix: /auth2/authorization
    # ????????? url ?? ???? RedirectUrl ???, ??? ServletContextPath???? /auth2/login.
    # http://localhost:9091/demo/auth2/login/gitee
    redirect-url-prefix: /auth2/login
    # ??????????, ???http://localhost:9090 ??? "http://127.0.0.1"?
    # redirectUrl ??? {domain}/{servletContextPath}/{redirectUrlPrefix}/{providerId}(ums.oauth.[qq/gitee/weibo])??
    domain: http://localhost:9091
    # ???????????????, ?????????, ???: "ROLE_USER"
    default-authorities: ROLE_USER
    # ?? JustAuth ???(HttpClient)??
    proxy:
      # ??????(HttpClient)??, ?? PT3S
      timeout: PT3S
      # ????????(HttpClient)??, ?? PT15S
      foreign-timeout: PT150S
    enable-user-connection-and-auth-token-table: true


#debug: true


